Agile09/Agile09/Models/CartItem.cs
using Agile09.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Agile09.Models
{
    [Serializable]
    public class CartItem
    {
        public Product Product { get; set; }
        public int Quantity { get; set; }
    }
}

Agile09/Agile09/Controllers/CartItemController.cs
using Agile09.Common;
using Agile09.DAO;
using Agile09.EF;
using Agile09.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Agile09.Controllers
{
    public class CartItemController : BaseController
    {
        // GET: CartItem
        public ActionResult Index()
        {
            var cart = Session[CommonConstants.CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
            return View(list);
        }
        // Thêm item vào giỏ hàng
        public ActionResult AddItem(long productID, int quantity)
        {
            var product = new ProductDAO().ViewDetail(productID);
            var cart = Session[CommonConstants.CartSession];
            if (cart != null)
            {
                var list = (List<CartItem>)cart;
                if (list.Exists(x => x.Product.ID == productID))
                {
                    foreach (var item in list)
                    {
                        if (item.Product.ID == productID)
                        {
                            item.Quantity += quantity;
                        }
                    }
                }
                else
                {
                    // Tạo mới đối tượng cart item
                    var item = new CartItem();
                    item.Product = product;
                    item.Quantity = quantity;
                    list.Add(item);

                }
                // Gán vào sesstion
                Session[CommonConstants.CartSession] = list;
            }
            else
            {
                // Tạo mới đối tượng cart item
                var item = new CartItem();
                item.Product = product;
                item.Quantity = quantity;
                var list = new List<CartItem>();
                // Gán vào sesstion
                list.Add(item);
                Session[CommonConstants.CartSession] = list;
            }
            return RedirectToAction("Index");
        }
        // Cập nhật giỏ hàng
        public JsonResult Update(string cartModel)
        {
            var jsonCart = new JavaScriptSerializer().Deserialize<List<CartItem>>(cartModel);
            var sessionCart = (List<CartItem>)Session[CommonConstants.CartSession];
            foreach (var item in sessionCart)
            {
                var jsonItem = jsonCart.SingleOrDefault(x => x.Product.ID == item.Product.ID);
                if (jsonItem != null)
                {
                    item.Quantity = jsonItem.Quantity;
                }
            }
            Session[CommonConstants.CartSession] = sessionCart;
            return Json(new
            {
                status = true
            });
        }
        // Xoá tất cả trong giỏ hàng
        public JsonResult DeleteAll()
        {
            Session[CommonConstants.CartSession] = null;
            return Json(new
            {
                status = true
            });
        }
        // Xoá 1 món trong giỏ hàng
        public JsonResult Delete(long id)
        {
            var sessionCart = (List<CartItem>)Session[CommonConstants.CartSession];
            sessionCart.RemoveAll(x => x.Product.ID == id);
            Session[CommonConstants.CartSession] = sessionCart;
            return Json(new
            {
                status = true
            });
        }
        //Thanh toán
        [HttpGet]
        public ActionResult Payment()
        {
            var cart = Session[CommonConstants.CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
            return View(list);
        }
        [HttpPost]
        public ActionResult Payment(string shipName, string mobile, string address, string email)
        {
            var order = new OrderProduct();
            order.CreatedDate = DateTime.Now;
            order.ShipAddress = address;
            order.ShipMobile = mobile;
            order.ShipName = shipName;
            order.ShipEmail = email;

            try
            {
                var id = new OrderDAO().Insert(order);
                var cart = (List<CartItem>)Session[CommonConstants.CartSession];
                var detailDAO = new OrderDetailDAO();
                decimal total = 0;

                //tạo thống kê
                //bool isEnough = true;

                foreach (var item in cart)
                {
                    var orderDetail = new OrderDetail();
                    orderDetail.ProductID = item.Product.ID;
                    orderDetail.OrderID = id;
                    orderDetail.Price = item.Product.Price;
                    orderDetail.Quantity = item.Quantity;
                    detailDAO.Insert(orderDetail);

                    total += (item.Product.Price.GetValueOrDefault(0) * item.Quantity);
                    //isEnough = new SalesProduct().SellProduct(item.Product.ID, item.Quantity);
                    //break;
                }
            }
            catch (Exception er)
            {
                //ghi log
                return Redirect("/loi-thanh-toan");
            }
            Session[CommonConstants.CartSession] = null;
            return Redirect("/hoan-thanh");
        }
        public ActionResult Success()
        {
            return View();
        }
        public ActionResult Error()
        {
            return View();
        }
    }
}

Agile09/Agile09/Views/CartItem/Index.cshtml
@model List<Agile09.Models.CartItem>
@{
    ViewBag.Title = "Giỏ Hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
    <script src="/Asset/Shop/js/Controller/cartController.js"></script>
}
<div class="breadcrumbs">
    <div class="container">
        <ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
            <li><a href="/"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Trang chủ</a></li>
            <li class="active">Giỏ hàng</li>
        </ol>
    </div>
</div>

<div class="products">
    <div class="container">
        <div class="agileinfo_single">
            <div class="newproducts-w3agile">
                <div class="container-fluid">
                    <h3>Danh sách giỏ hàng</h3><br />
                    <div style="margin-bottom:5px">
                        <button style="margin-bottom:5px" id="btnContinue" class="btn btn-primary">Tiếp tục mua hàng</button>
                        <button style="margin-bottom:5px" id="btnUpdate" class="btn btn-warning">Cập nhật giỏ hàng</button>
                        <button style="margin-bottom:5px" id="btnDeleteAll" class="btn btn-danger">Xóa giỏ hàng</button>
                        <button style="margin-bottom:5px" id="btnPayment" class="btn btn-success">Thanh toán</button>
                    </div>
                    @if (Model.Count() > 0)
                    {
                        <div class="table-responsive">
                            <table class="table table-bordered text-center" id="" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>Mã SP</th>
                                        <th>Tên SP</th>
                                        <th>Ảnh SP</th>
                                        <th>Số lượng</th>
                                        <th>Đơn giá (VNĐ)</th>
                                        <th>Thành tiền (VNĐ)</th>
                                        <th>Trạng thái</th>
                                        <th>Thao tác</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>Mã SP</th>
                                        <th>Tên SP</th>
                                        <th>Ảnh SP</th>
                                        <th>Số lượng</th>
                                        <th>Đơn giá (VNĐ)</th>
                                        <th>Thành tiền (VNĐ)</th>
                                        <th>Trạng thái</th>
                                        <th>Thao tác</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr id="row_@item.Product.ID">
                                            <td>@item.Product.ID</td>
                                            <td>@item.Product.Name</td>
                                            <td><img src="@item.Product.Image" width="100" /></td>
                                            <td><input type="text" class="txtQuantity form-control" data-id="@item.Product.ID" value="@item.Quantity" /></td>
                                            <td>@item.Product.Price.GetValueOrDefault(0).ToString("N0")</td>
                                            <td>@((item.Product.Price.GetValueOrDefault(0) * item.Quantity).ToString("N0"))</td>
                                            <td><a href="#" style="text-decoration:none" class="btnActive" data-id="@item.Product.ID">Đã thêm</a></td>
                                            <td><a href="#" class="btn-delete" data-id="@item.Product.ID">Xóa</a></td>
                                        </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                    }
                    else
                    {
                        <p class="text-center alert alert-info">Chưa có sản phẩm nào trong giỏ hàng. <a href="/">Về trang chủ</a></p>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Agile09/Agile09/Views/CartItem/Payment.cshtml
@model List<Agile09.Models.CartItem>
@{
    ViewBag.Title = "Thanh Toán Hóa Đơn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="breadcrumbs">
    <div class="container">
        <ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
            <li><a href="/"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Trang chủ</a></li>
            <li class="active">Thanh toán</li>
        </ol>
    </div>
</div>

<div class="products">
    <div class="container">
        <div class="agileinfo_single">
            <div class="newproducts-w3agile">
                <div class="container-fluid">
                    <h3>Thanh toán</h3><br />
                    @if (Model.Count() > 0)
                    {
                        <div class="table-responsive">
                            <table class="table table-bordered text-center" id="" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>Mã SP</th>
                                        <th>Tên SP</th>
                                        <th>Ảnh SP</th>
                                        <th>Số lượng</th>
                                        <th>Đơn giá (VNĐ)</th>
                                        <th>Thành tiền (VNĐ)</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>Mã SP</th>
                                        <th>Tên SP</th>
                                        <th>Ảnh SP</th>
                                        <th>Số lượng</th>
                                        <th>Đơn giá (VNĐ)</th>
                                        <th>Thành tiền (VNĐ)</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr id="row_@item.Product.ID">
                                            <td>@item.Product.ID</td>
                                            <td>@item.Product.Name</td>
                                            <td><img src="@item.Product.Image" width="100" /></td>
                                            <td><input type="text" class="txtQuantity form-control" data-id="@item.Product.ID" value="@item.Quantity" disabled /></td>
                                            <td>@item.Product.Price.GetValueOrDefault(0).ToString("N0")</td>
                                            <td>@((item.Product.Price.GetValueOrDefault(0) * item.Quantity).ToString("N0"))</td>

                                        </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                    }
                    else
                    {
                        <div class="alert alert-danger text-center">Bạn chưa có sản phẩm nào để thanh toán <a href="/">Tiếp tục mua hàng</a></div>
                    }
                </div>
            </div>
        </div>
    </div>
    @if (Model.Count > 0)
    {
        <div class="container">
            <div class="agileinfo_single">
                <div class="newproducts-w3agile">
                    <div class="container-fluid">
                        <h3>Form điền thông tin</h3><br />
                        @using (Html.BeginForm("Payment", "CartItem", FormMethod.Post))
                        {
                            <div class="form-group">
                                <label for="shipName">Họ và tên</label>
                                <input type="text" name="shipName" class="form-control" required />
                            </div>
                            <div class="form-group">
                                <label for="mobile">Điện thoại</label>
                                <input type="text" name="mobile" class="form-control" required />
                            </div>
                            <div class="form-group">
                                <label for="address">Địa chỉ</label>
                                <input type="text" name="address" class="form-control" required />
                            </div>
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" name="email" class="form-control" />
                            </div>
                            <button type="submit" class="btn btn-primary">Gửi đơn hàng</button>
                        }
                    </div>
                </div>
            </div>
        </div>

    }
</div>

Agile09/Agile09/Views/CartItem/Success.cshtml
@{
    ViewBag.Title = "Thanh Toán Thành Công";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="alert alert-success text-center">Bạn đã thanh toán thành công. <a href="/">Tiếp tục mua hàng</a></div>